# Generated by Django 2.1.1 on 2018-10-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_name', models.CharField(max_length=30)),
                ('reference_email', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='formsubmit',
            name='arrive',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmit',
            name='depart',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmit',
            name='pincode',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
