# Generated by Django 2.1.1 on 2018-11-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='applied_for_member',
            field=models.BooleanField(default=False),
        ),
    ]
