# Generated by Django 2.1.1 on 2018-10-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20181006_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmit',
            name='reference_email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='formsubmit',
            name='reference_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
