# Generated by Django 2.1.5 on 2019-02-18 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_feedbacksubmit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacksubmit',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
