# Generated by Django 2.1.1 on 2018-10-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20181007_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingID', models.CharField(blank=True, max_length=15, null=True)),
                ('roomID', models.CharField(blank=True, max_length=15, null=True)),
                ('arrive', models.DateField(blank=True, null=True)),
                ('depart', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomID', models.CharField(blank=True, max_length=15, null=True)),
                ('room_type', models.CharField(blank=True, max_length=5, null=True)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='formsubmit',
            name='room_type',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmit',
            name='depart',
            field=models.DateField(blank=True, null=True),
        ),
    ]
