# Generated by Django 2.1.1 on 2018-10-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20181012_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
