# Generated by Django 2.1.1 on 2018-10-23 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_auto_20181022_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['pk']},
        ),
    ]
