# Generated by Django 2.1.1 on 2018-10-23 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_auto_20181023_0814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
    ]
