# Generated by Django 2.1.3 on 2019-02-11 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingID', models.CharField(blank=True, max_length=15, null=True)),
                ('roomID', models.CharField(blank=True, max_length=15, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('arrive', models.DateField(blank=True, null=True)),
                ('depart', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('street', models.TextField(max_length=300)),
                ('city', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=30)),
                ('pincode', models.CharField(blank=True, max_length=30, null=True)),
                ('arrive', models.DateField(blank=True, null=True)),
                ('depart', models.DateField(blank=True, null=True)),
                ('reference_name', models.CharField(blank=True, max_length=30, null=True)),
                ('reference_email', models.CharField(blank=True, max_length=30, null=True)),
                ('room_type', models.CharField(blank=True, max_length=5, null=True)),
                ('reference_verified', models.BooleanField(default=False)),
                ('director_verified', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('booking_mail_sent', models.BooleanField(default=False)),
                ('admin_verified', models.BooleanField(default=False)),
                ('bookingtable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.BookingTable')),
                ('userbookings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
